// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLZYbqyDX3YwKsWAG9WypBaTFkirpGGrY',
    appId: '1:1088949266751:web:8e166e181e1df1fae8cb8a',
    messagingSenderId: '1088949266751',
    projectId: 'franchisemarketturkiye-e51a1',
    authDomain: 'franchisemarketturkiye-e51a1.firebaseapp.com',
    storageBucket: 'franchisemarketturkiye-e51a1.firebasestorage.app',
    measurementId: 'G-NCL363BWYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr3-LFAD2LAZPU0XafzbIcGxR3ZV4Qvog',
    appId: '1:1088949266751:android:5462b42344c0fe36e8cb8a',
    messagingSenderId: '1088949266751',
    projectId: 'franchisemarketturkiye-e51a1',
    storageBucket: 'franchisemarketturkiye-e51a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNxJw9Q7IQsgikxMCz-jDlrrgCp45bPSk',
    appId: '1:1088949266751:ios:b6e5f092b6f1a713e8cb8a',
    messagingSenderId: '1088949266751',
    projectId: 'franchisemarketturkiye-e51a1',
    storageBucket: 'franchisemarketturkiye-e51a1.firebasestorage.app',
    iosBundleId: 'com.smartmetrics.franchisemarketturkiyeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNxJw9Q7IQsgikxMCz-jDlrrgCp45bPSk',
    appId: '1:1088949266751:ios:07fbc22ccbb6d3e8e8cb8a',
    messagingSenderId: '1088949266751',
    projectId: 'franchisemarketturkiye-e51a1',
    storageBucket: 'franchisemarketturkiye-e51a1.firebasestorage.app',
    iosBundleId: 'com.smartmetrics.franchisemarketturkiye',
  );
}